export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const RECEIVE_CATEGORY = 'RECEIVE_CATEGORY';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT';

export const CREATE_CART = "CREATE_CART";
export const RECEIVE_ALL_ORDERS = 'RECEIVE_ALL_ORDERS';
export const RECEIVE_ALL_ORDERS_FOR_USER = 'RECEIVE_ALL_ORDERS_FOR_USER';
export const ADD_PRODUCT_TO_ORDER = 'ADD_PRODUCT_TO_ORDER';
export const REMOVE_PRODUCT_FROM_ORDER = 'REMOVE_PRODUCT_FROM_ORDER';
export const CHECKOUT_ORDER = 'CHECKOUT_ORDER';
export const CHANGE_ORDER_TO_COMPLETED = 'CHANGE_ORDER_TO_COMPLETED';
export const REMOVE_ORDER = 'REMOVE_ORDER';


export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';
export const CREATE_USER = 'CREATE_USER';

export const SWITCH_LOCATION = 'SWITCH_LOCATION';
